### ISSUE TITLE
Tukic Case-Insensitive Locales

### ISSUE THREAD

**Issue by indolering** [nicowilliams/ietf-fs-i18n#4]
From the Unicode specification: [Chapter 5.18, Caseless Matching](http://www.unicode.org/versions/Unicode11.0.0/ch05.pdf):

> In most environments, such as in file systems, text is not and cannot be tagged with language information. In such cases, the language-specific mappings must not be used. Otherwise, data structures such as B-trees might be built based on one set of case foldings and used based on a different set of case foldings. This discrepancy would cause those data structures to become corrupt. For such environments, a constant, language-independent, default case folding is required.

I thought we had discussed this, but I can't find any mentions of it in the tickets or email.

After doing a deep dive, I **think** that a Turkic locale would be an instance of over inclusivity: when actions designed to accommodate a traditionally marginalized group results in further marginalization.  I believe this is the case because Turkic-specific case-folding would be a fairly minor usability improvement at the cost of creating a filesystem tree that is incompatible with everyone else.

I'll comment some more later.

**Comment by nicowilliams** [comment]
Well, this is only for case-insensitivity.  I don't like case-insensitivity myself, but if you want it, you get to choose whether to enable Turkic case-insensitivity or not, on a per-filesystem, or even per-directory basis.

There isn't anything for us to do here other than note the problem and the lack of a perfect solution.

**Comment by nicowilliams** [comment]
I.e., nothing about filesystems causes this problem, so it's not something we should be particularly upset about, just document it.

**Comment by indolering** [comment]
But the Unicode guidelines specifically states that this **must** not be used, I think the IETF draft should at echo this recommendation by least stating that locale information SHOULD NOT be used.
